import PropTypes from "prop-types";

const FrameComponent1 = ({ className = "" }) => {
  return (
    <div
      className={`flex-1 shadow-[0px_0px_10px_rgba(42,_63,_77,_0.08)] rounded-lg bg-nds-refresh-neutrals-00white flex flex-col items-start justify-start py-6 px-8 box-border gap-[22px] max-w-full h-auto hover:bg-nds-refresh-neutrals-00white hover:flex hover:flex-1 hover:h-auto hover:flex-col gap-[22px] hover:items-start hover:justify-start hover:rounded-lg hover:py-6 hover:px-8 hover:box-border hover:shadow-[0px_0px_10px_rgba(42,_63,_77,_0.08)] hover:max-w-full flex-1 shadow-[0px_0px_10px_rgba(42,_63,_77,_0.08)] rounded-lg bg-nds-refresh-neutrals-00white flex flex-col items-start justify-start py-6 px-8 box-border gap-[22px] max-w-full h-auto text-right text-sm text-primary-accent-orange-900 hover:bg-nds-refresh-neutrals-00white hover:flex hover:flex-1 hover:h-auto hover:flex-col gap-[22px] hover:items-start hover:justify-start hover:rounded-lg hover:py-6 hover:px-8 hover:box-border hover:shadow-[0px_0px_10px_rgba(42,_63,_77,_0.08)] hover:max-w-full ${className}`}
    >
      <div className="self-stretch flex flex-row items-start justify-start gap-6 max-w-full w-auto h-auto hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-row gap-6 hover:items-start hover:justify-start hover:max-w-full mq975:flex-wrap self-stretch flex flex-row items-start justify-start gap-6 max-w-full w-auto h-auto hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-row gap-6 hover:items-start hover:justify-start hover:max-w-full mq975:flex-wrap">
        <div className="w-[234px] flex flex-col items-start justify-start pt-[86px] px-0 pb-0 box-border min-w-[234] h-auto gap-0 [transform:rotate(0deg)] hover:flex hover:w-[234px] hover:h-auto hover:flex-col gap-0 hover:items-start hover:justify-start hover:[transform:rotate(0deg)] hover:pt-[86px] hover:px-0 hover:pb-0 hover:box-border hover:min-w-[234] mq975:flex-1 w-[234px] flex flex-col items-start justify-start pt-[86px] px-0 pb-0 box-border min-w-[234] h-auto gap-0 [transform:rotate(0deg)] hover:flex hover:w-[234px] hover:h-auto hover:flex-col gap-0 hover:items-start hover:justify-start hover:[transform:rotate(0deg)] hover:pt-[86px] hover:px-0 hover:pb-0 hover:box-border hover:min-w-[234] mq975:flex-1">
          <div className="self-stretch flex flex-row items-start justify-start w-auto h-auto gap-2 hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-row gap-2 hover:items-start hover:justify-start self-stretch flex flex-row items-start justify-start w-auto h-auto gap-2 hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-row gap-2 hover:items-start hover:justify-start">
            <h2 className="m-0 flex-1 relative text-inherit tracking-[-0.5px] leading-[29px] font-normal font-[inherit] flex h-auto hover:font-nds-typography-library-body-text-small hover:text-5xl hover:tracking-[-0.5px] hover:leading-[29px] hover:text-left hover:text-black hover:flex hover:flex-1 hover:h-auto mq450:text-lgi mq450:leading-[23px] m-0 flex-1 relative text-inherit tracking-[-0.5px] leading-[29px] font-normal font-[inherit] flex h-auto hover:font-nds-typography-library-body-text-small hover:text-5xl hover:tracking-[-0.5px] hover:leading-[29px] hover:text-left hover:text-black hover:flex hover:flex-1 hover:h-auto mq450:text-lgi mq450:leading-[23px]">
              Overall Building Score
            </h2>
          </div>
        </div>
        <div className="flex-1 flex flex-col items-start justify-start py-2 pl-[286px] pr-2 box-border gap-2 min-w-[403] max-w-full h-auto text-29xl hover:flex hover:flex-1 hover:h-auto hover:flex-col gap-2 hover:items-start hover:justify-start hover:py-2 hover:pl-[286px] hover:pr-2 hover:box-border hover:min-w-[403] hover:max-w-full mq450:pl-5 mq450:box-border mq725:pl-[143px] mq725:box-border mq725:min-w-full flex-1 flex flex-col items-start justify-start py-2 pl-[286px] pr-2 box-border gap-2 min-w-[403] max-w-full h-auto hover:flex hover:flex-1 hover:h-auto hover:flex-col gap-2 hover:items-start hover:justify-start hover:py-2 hover:pl-[286px] hover:pr-2 hover:box-border hover:min-w-[403] hover:max-w-full mq450:pl-5 mq450:box-border mq725:pl-[143px] mq725:box-border mq725:min-w-full">
          <div className="self-stretch h-[163px] flex flex-row items-start justify-start w-auto hover:flex hover:self-stretch hover:w-auto hover:h-[163px] hover:flex-row hover:items-start hover:justify-start self-stretch h-[163px] flex flex-row items-start justify-start w-auto hover:flex hover:self-stretch hover:w-auto hover:h-[163px] hover:flex-row hover:items-start hover:justify-start">
            <div className="h-[163px] w-[326px] relative flex gap-0 items-start justify-start [transform:rotate(0deg)] hover:flex hover:w-[326px] hover:h-[163px] gap-0 hover:items-start hover:justify-start hover:[transform:rotate(0deg)] h-[163px] w-[326px] relative flex gap-0 items-start justify-start [transform:rotate(0deg)] hover:flex hover:w-[326px] hover:h-[163px] gap-0 hover:items-start hover:justify-start hover:[transform:rotate(0deg)]">
              <img
                className="absolute top-[0px] left-[0px] w-full h-full flex hover:flex hover:w-full hover:h-full absolute top-[0px] left-[0px] w-full h-full flex hover:flex hover:w-full hover:h-full"
                loading="lazy"
                alt=""
                src="/vector.svg"
              />
              <div className="absolute top-[58.5px] left-[106px] w-[113px] h-[97px] flex flex-col items-start justify-start gap-1 z-[1] hover:flex hover:w-[113px] hover:h-[97px] hover:flex-col gap-1 hover:items-start hover:justify-start absolute top-[58.5px] left-[106px] w-[113px] h-[97px] flex flex-col items-start justify-start gap-1 z-[1] hover:flex hover:w-[113px] hover:h-[97px] hover:flex-col gap-1 hover:items-start hover:justify-start">
                <div className="w-[113px] h-[68px] flex flex-row items-start justify-start py-0 px-5 box-border gap-0 [transform:rotate(0deg)] hover:flex hover:w-[113px] hover:h-[68px] hover:flex-row gap-0 hover:items-start hover:justify-start hover:[transform:rotate(0deg)] hover:py-0 hover:px-5 hover:box-border w-[113px] h-[68px] flex flex-row items-start justify-start py-0 px-5 box-border gap-0 [transform:rotate(0deg)] hover:flex hover:w-[113px] hover:h-[68px] hover:flex-row gap-0 hover:items-start hover:justify-start hover:[transform:rotate(0deg)] hover:py-0 hover:px-5 hover:box-border">
                  <div className="h-[68px] w-[72px] flex flex-row items-start justify-start p-2.5 box-border gap-2.5 hover:flex hover:w-[72px] hover:h-[68px] hover:flex-row gap-2.5 hover:items-start hover:justify-start hover:p-2.5 hover:box-border h-[68px] w-[72px] flex flex-row items-start justify-start p-2.5 box-border gap-2.5 hover:flex hover:w-[72px] hover:h-[68px] hover:flex-row gap-2.5 hover:items-start hover:justify-start hover:p-2.5 hover:box-border">
                    <div className="h-auto w-[52px] relative tracking-[-1.5px] leading-[48px] font-light flex hover:font-light hover:font-nds-typography-library-body-text-small hover:text-29xl hover:tracking-[-1.5px] hover:leading-[48px] hover:text-left hover:text-black hover:flex hover:w-[52px] hover:h-auto mq975:text-19xl mq975:leading-[38px] mq450:text-10xl mq450:leading-[29px] h-auto w-[52px] relative tracking-[-1.5px] leading-[48px] font-light flex hover:font-light hover:font-nds-typography-library-body-text-small hover:text-29xl hover:tracking-[-1.5px] hover:leading-[48px] hover:text-left hover:text-black hover:flex hover:w-[52px] hover:h-auto mq975:text-19xl mq975:leading-[38px] mq450:text-10xl mq450:leading-[29px]">
                      75
                    </div>
                  </div>
                </div>
                <div className="w-[113px] h-[] rounded-mini bg-secondary-colors-warning-yellow-300 flex flex-row items-start justify-start py-1 px-[30px] box-border whitespace-nowrap gap-2.5 text-sm text-primary-accent-orange-900 hover:bg-secondary-colors-warning-yellow-300 hover:flex hover:w-[113px] hover:flex-row gap-2.5 hover:items-start hover:justify-start hover:rounded-mini hover:py-1 hover:px-[30px] hover:box-border hover:whitespace-nowrap w-[113px] h-[] rounded-mini bg-secondary-colors-warning-yellow-300 flex flex-row items-start justify-start py-1 px-[30px] box-border whitespace-nowrap gap-2.5 hover:bg-secondary-colors-warning-yellow-300 hover:flex hover:w-[113px] hover:flex-row gap-2.5 hover:items-start hover:justify-start hover:rounded-mini hover:py-1 hover:px-[30px] hover:box-border hover:whitespace-nowrap">
                  <div className="h-auto w-[53px] relative tracking-[-0.15px] leading-[17px] font-light flex hover:font-light hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.15px] hover:leading-[17px] hover:text-left hover:text-primary-accent-orange-900 hover:flex hover:w-[53px] hover:h-auto h-auto w-[53px] relative tracking-[-0.15px] leading-[17px] font-light flex hover:font-light hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.15px] hover:leading-[17px] hover:text-left hover:text-primary-accent-orange-900 hover:flex hover:w-[53px] hover:h-auto">{`Average `}</div>
                </div>
              </div>
            </div>
          </div>
          <div className="self-stretch flex flex-row items-start justify-start gap-4 w-auto h-auto text-xs text-main-grey-700 hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-row gap-4 hover:items-start hover:justify-start mq450:flex-wrap self-stretch flex flex-row items-start justify-start gap-4 w-auto h-auto text-xs text-main-grey-700 hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-row gap-4 hover:items-start hover:justify-start mq450:flex-wrap">
            <div className="flex-1 relative leading-[14px] flex min-w-[101] h-auto hover:font-nds-typography-library-body-text-small hover:text-xs hover:leading-[14px] hover:text-left hover:text-main-grey-700 hover:flex hover:flex-1 hover:h-auto hover:min-w-[101] flex-1 relative leading-[14px] flex min-w-[101] h-auto hover:font-nds-typography-library-body-text-small hover:text-xs hover:leading-[14px] hover:text-left hover:text-main-grey-700 hover:flex hover:flex-1 hover:h-auto hover:min-w-[101]">
              POOR
            </div>
            <div className="flex-1 relative leading-[14px] text-right flex min-w-[101] h-auto hover:font-nds-typography-library-body-text-small hover:text-xs hover:leading-[14px] hover:text-right hover:text-main-grey-700 hover:flex hover:flex-1 hover:h-auto hover:min-w-[101] flex-1 relative leading-[14px] flex min-w-[101] h-auto hover:font-nds-typography-library-body-text-small hover:text-xs hover:leading-[14px] hover:text-right hover:text-main-grey-700 hover:flex hover:flex-1 hover:h-auto hover:min-w-[101]">
              EXCELLENT
            </div>
          </div>
        </div>
      </div>
      <div className="self-stretch flex flex-row items-start justify-end w-auto h-auto gap-6 text-xs text-nds-colors-library-primary-main-grey600 hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-row gap-6 hover:items-start hover:justify-end self-stretch flex flex-row items-start justify-end w-auto h-auto gap-6 text-xs text-nds-colors-library-primary-main-grey600 hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-row gap-6 hover:items-start hover:justify-end">
        <div className="w-[136px] flex flex-row items-start justify-start gap-spacing-space-sm h-auto hover:flex hover:w-[136px] hover:h-auto hover:flex-row gap-spacing-space-sm hover:items-start hover:justify-start w-[136px] flex flex-row items-start justify-start gap-spacing-space-sm h-auto hover:flex hover:w-[136px] hover:h-auto hover:flex-row gap-spacing-space-sm hover:items-start hover:justify-start">
          <div className="flex flex-row items-start justify-start gap-1.5 w-auto [align-self:unset] h-auto hover:flex hover:w-auto hover:[align-self:unset] hover:h-auto hover:flex-row gap-1.5 hover:items-start hover:justify-start flex flex-row items-start justify-start gap-1.5 w-auto [align-self:unset] h-auto hover:flex hover:w-auto hover:[align-self:unset] hover:h-auto hover:flex-row gap-1.5 hover:items-start hover:justify-start">
            <div className="flex flex-col items-start justify-start pt-px px-0 pb-0 box-border w-auto [align-self:unset] h-auto gap-0 [transform:rotate(0deg)] hover:flex hover:w-auto hover:[align-self:unset] hover:h-auto hover:flex-col gap-0 hover:items-start hover:justify-start hover:[transform:rotate(0deg)] hover:pt-px hover:px-0 hover:pb-0 hover:box-border flex flex-col items-start justify-start pt-px px-0 pb-0 box-border w-auto [align-self:unset] h-auto gap-0 [transform:rotate(0deg)] hover:flex hover:w-auto hover:[align-self:unset] hover:h-auto hover:flex-col gap-0 hover:items-start hover:justify-start hover:[transform:rotate(0deg)] hover:pt-px hover:px-0 hover:pb-0 hover:box-border">
              <div className="relative leading-[14px] flex min-w-[8] w-auto [align-self:unset] h-auto hover:font-nds-typography-library-body-text-small hover:text-xs hover:leading-[14px] hover:text-left hover:text-nds-colors-library-primary-main-grey600 hover:flex hover:w-auto hover:[align-self:unset] hover:h-auto hover:min-w-[8] relative leading-[14px] flex min-w-[8] w-auto [align-self:unset] h-auto hover:font-nds-typography-library-body-text-small hover:text-xs hover:leading-[14px] hover:text-left hover:text-nds-colors-library-primary-main-grey600 hover:flex hover:w-auto hover:[align-self:unset] hover:h-auto hover:min-w-[8]">
                0
              </div>
            </div>
            <div className="h-4 w-4 relative rounded-spacing-space-sm bg-orangered flex hover:bg-orangered hover:flex hover:w-4 hover:h-4 hover:rounded-spacing-space-sm h-4 w-4 relative rounded-spacing-space-sm bg-orangered flex hover:bg-orangered hover:flex hover:w-4 hover:h-4 hover:rounded-spacing-space-sm" />
          </div>
          <div className="h-4 w-4 rounded bg-chocolate flex flex-row items-center justify-start gap-1.5 hover:bg-chocolate hover:flex hover:w-4 hover:h-4 hover:flex-row gap-1.5 hover:items-center hover:justify-start hover:rounded h-4 w-4 rounded bg-chocolate flex flex-row items-center justify-start gap-1.5 hover:bg-chocolate hover:flex hover:w-4 hover:h-4 hover:flex-row gap-1.5 hover:items-center hover:justify-start hover:rounded" />
          <div className="h-4 w-4 rounded bg-goldenrod flex flex-row items-center justify-start gap-1.5 hover:bg-goldenrod hover:flex hover:w-4 hover:h-4 hover:flex-row gap-1.5 hover:items-center hover:justify-start hover:rounded h-4 w-4 rounded bg-goldenrod flex flex-row items-center justify-start gap-1.5 hover:bg-goldenrod hover:flex hover:w-4 hover:h-4 hover:flex-row gap-1.5 hover:items-center hover:justify-start hover:rounded" />
          <div className="h-4 w-4 rounded bg-khaki flex flex-row items-center justify-start gap-1.5 hover:bg-khaki hover:flex hover:w-4 hover:h-4 hover:flex-row gap-1.5 hover:items-center hover:justify-start hover:rounded h-4 w-4 rounded bg-khaki flex flex-row items-center justify-start gap-1.5 hover:bg-khaki hover:flex hover:w-4 hover:h-4 hover:flex-row gap-1.5 hover:items-center hover:justify-start hover:rounded" />
          <div className="flex-1 flex flex-row items-start justify-start gap-1.5 h-auto text-right hover:flex hover:flex-1 hover:h-auto hover:flex-row gap-1.5 hover:items-start hover:justify-start flex-1 flex flex-row items-start justify-start gap-1.5 h-auto hover:flex hover:flex-1 hover:h-auto hover:flex-row gap-1.5 hover:items-start hover:justify-start">
            <div className="h-4 w-4 relative rounded-spacing-space-sm bg-lightgreen flex hover:bg-lightgreen hover:flex hover:w-4 hover:h-4 hover:rounded-spacing-space-sm h-4 w-4 relative rounded-spacing-space-sm bg-lightgreen flex hover:bg-lightgreen hover:flex hover:w-4 hover:h-4 hover:rounded-spacing-space-sm" />
            <div className="flex-1 flex flex-col items-start justify-start pt-px px-0 pb-0 box-border h-auto gap-0 [transform:rotate(0deg)] hover:flex hover:flex-1 hover:h-auto hover:flex-col gap-0 hover:items-start hover:justify-start hover:[transform:rotate(0deg)] hover:pt-px hover:px-0 hover:pb-0 hover:box-border flex-1 flex flex-col items-start justify-start pt-px px-0 pb-0 box-border h-auto gap-0 [transform:rotate(0deg)] hover:flex hover:flex-1 hover:h-auto hover:flex-col gap-0 hover:items-start hover:justify-start hover:[transform:rotate(0deg)] hover:pt-px hover:px-0 hover:pb-0 hover:box-border">
              <div className="self-stretch relative leading-[14px] flex min-w-[20] w-auto h-auto hover:font-nds-typography-library-body-text-small hover:text-xs hover:leading-[14px] hover:text-right hover:text-nds-colors-library-primary-main-grey600 hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:min-w-[20] self-stretch relative leading-[14px] flex min-w-[20] w-auto h-auto hover:font-nds-typography-library-body-text-small hover:text-xs hover:leading-[14px] hover:text-right hover:text-nds-colors-library-primary-main-grey600 hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:min-w-[20]">
                100
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

FrameComponent1.propTypes = {
  className: PropTypes.string,
};

export default FrameComponent1;
