import PropTypes from "prop-types";

const NotificationPanel = ({ className = "" }) => {
  return (
    <footer
      className={`self-stretch rounded-lg bg-whitesmoke flex flex-col items-start justify-start p-6 box-border max-w-full w-auto h-auto gap-0 text-left text-lg text-nds-refresh-neutrals-500 font-nds-typography-library-body-text-small hover:bg-whitesmoke hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-col gap-0 hover:items-start hover:justify-start hover:rounded-lg hover:p-6 hover:box-border hover:max-w-full mq725:pt-5 mq725:pb-5 mq725:box-border self-stretch rounded-lg bg-whitesmoke flex flex-col items-start justify-start p-6 box-border max-w-full w-auto h-auto gap-0 text-center text-sm text-gray-100 font-nexus-theme-title-medium hover:bg-whitesmoke hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-col gap-0 hover:items-start hover:justify-start hover:rounded-lg hover:p-6 hover:box-border hover:max-w-full mq725:pt-5 mq725:pb-5 mq725:box-border ${className}`}
    >
      <div className="self-stretch bg-nds-refresh-neutrals-00white overflow-hidden flex flex-row items-center justify-start p-4 box-border max-w-full w-auto h-auto gap-4 text-5xl text-black hover:bg-nds-refresh-neutrals-00white hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-row gap-4 hover:items-center hover:justify-start hover:p-4 hover:box-border hover:max-w-full self-stretch bg-nds-refresh-neutrals-00white overflow-hidden flex flex-row items-center justify-start p-4 box-border max-w-full w-auto h-auto gap-4 text-steelblue hover:bg-nds-refresh-neutrals-00white hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-row gap-4 hover:items-center hover:justify-start hover:p-4 hover:box-border hover:max-w-full">
        <div className="flex-1 flex flex-row items-center justify-between max-w-full gap-5 h-auto hover:flex hover:flex-1 hover:h-auto hover:flex-row gap-5 hover:items-center hover:justify-between hover:max-w-full mq450:flex-wrap flex-1 flex flex-row items-center justify-between max-w-full gap-5 h-auto hover:flex hover:flex-1 hover:h-auto hover:flex-row gap-5 hover:items-center hover:justify-between hover:max-w-full mq450:flex-wrap">
          <div className="w-[90px] flex flex-col items-start justify-center gap-1 h-auto hover:flex hover:w-[90px] hover:h-auto hover:flex-col gap-1 hover:items-start hover:justify-center w-[90px] flex flex-col items-start justify-center gap-1 h-auto hover:flex hover:w-[90px] hover:h-auto hover:flex-col gap-1 hover:items-start hover:justify-center">
            <h2 className="m-0 w-[85px] relative text-inherit tracking-[-0.5px] leading-[29px] font-normal font-[inherit] flex h-auto hover:font-nds-typography-library-body-text-small hover:text-5xl hover:tracking-[-0.5px] hover:leading-[29px] hover:text-left hover:text-black hover:flex hover:w-[85px] hover:h-auto mq450:text-lgi mq450:leading-[23px] m-0 w-[85px] relative text-inherit tracking-[-0.5px] leading-[29px] font-normal font-[inherit] flex h-auto hover:font-nds-typography-library-body-text-small hover:text-5xl hover:tracking-[-0.5px] hover:leading-[29px] hover:text-left hover:text-black hover:flex hover:w-[85px] hover:h-auto mq450:text-lgi mq450:leading-[23px]">
              Insights
            </h2>
            <div className="self-stretch relative text-sm tracking-[-0.5px] leading-[17px] flex w-auto h-auto hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.5px] hover:leading-[17px] hover:text-left hover:text-black hover:flex hover:self-stretch hover:w-auto hover:h-auto self-stretch relative tracking-[-0.5px] leading-[17px] flex w-auto h-auto hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.5px] hover:leading-[17px] hover:text-left hover:text-black hover:flex hover:self-stretch hover:w-auto hover:h-auto">
              Priority Events
            </div>
          </div>
          <div className="rounded overflow-hidden flex flex-row items-center justify-center w-auto [align-self:unset] h-auto gap-1 text-base text-steelblue font-nexus-theme-title-medium hover:flex hover:w-auto hover:[align-self:unset] hover:h-auto hover:flex-row gap-1 hover:items-center hover:justify-center hover:rounded rounded overflow-hidden flex flex-row items-center justify-center w-auto [align-self:unset] h-auto gap-1 text-base hover:flex hover:w-auto hover:[align-self:unset] hover:h-auto hover:flex-row gap-1 hover:items-center hover:justify-center hover:rounded">
            <div className="relative leading-[24px] font-medium flex min-w-[82] w-auto [align-self:unset] h-auto hover:font-medium hover:font-nexus-theme-title-medium hover:text-base hover:leading-[24px] hover:text-left hover:text-steelblue hover:flex hover:w-auto hover:[align-self:unset] hover:h-auto hover:min-w-[82] relative leading-[24px] font-medium flex min-w-[82] w-auto [align-self:unset] h-auto hover:font-medium hover:font-nexus-theme-title-medium hover:text-base hover:leading-[24px] hover:text-left hover:text-steelblue hover:flex hover:w-auto hover:[align-self:unset] hover:h-auto hover:min-w-[82]">
              Dismiss all
            </div>
          </div>
        </div>
      </div>
      <div className="self-stretch shadow-[0px_0px_0px_1px_#e7ecf0] bg-nds-refresh-neutrals-00white overflow-hidden flex flex-col items-start justify-center p-4 box-border min-h-[48] w-auto h-auto gap-0 hover:bg-nds-refresh-neutrals-00white hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-col gap-0 hover:items-start hover:justify-center hover:p-4 hover:box-border hover:shadow-[0px_0px_0px_1px_#e7ecf0] hover:min-h-[48] self-stretch shadow-[0px_0px_0px_1px_#e7ecf0] bg-nds-refresh-neutrals-00white overflow-hidden flex flex-col items-start justify-center p-4 box-border min-h-[48] w-auto h-auto gap-0 hover:bg-nds-refresh-neutrals-00white hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-col gap-0 hover:items-start hover:justify-center hover:p-4 hover:box-border hover:shadow-[0px_0px_0px_1px_#e7ecf0] hover:min-h-[48]">
        <div className="self-stretch h-[99px] flex flex-row items-start justify-end gap-4 w-auto hover:flex hover:self-stretch hover:w-auto hover:h-[99px] hover:flex-row gap-4 hover:items-start hover:justify-end self-stretch h-[99px] flex flex-row items-start justify-end gap-4 w-auto hover:flex hover:self-stretch hover:w-auto hover:h-[99px] hover:flex-row gap-4 hover:items-start hover:justify-end">
          <img
            className="h-[17.5px] w-[17.5px] relative bg-nds-colors-library-secondary-accent-blue600 flex hover:bg-nds-colors-library-secondary-accent-blue600 hover:flex hover:w-[17.5px] hover:h-[17.5px] h-[17.5px] w-[17.5px] relative bg-nds-colors-library-secondary-accent-blue600 flex hover:bg-nds-colors-library-secondary-accent-blue600 hover:flex hover:w-[17.5px] hover:h-[17.5px]"
            alt=""
            src="/vector-3.svg"
          />
          <div className="h-[99px] flex-1 flex flex-row flex-wrap items-center justify-end gap-4 hover:flex hover:flex-1 hover:h-[99px] hover:flex-row hover:flex-wrap gap-4 hover:items-center hover:justify-end h-[99px] flex-1 flex flex-row flex-wrap items-center justify-end gap-4 hover:flex hover:flex-1 hover:h-[99px] hover:flex-row hover:flex-wrap gap-4 hover:items-center hover:justify-end">
            <div className="h-[99px] flex-1 flex flex-row items-start justify-start min-w-[200] gap-2 hover:flex hover:flex-1 hover:h-[99px] hover:flex-row gap-2 hover:items-start hover:justify-start hover:min-w-[200] h-[99px] flex-1 flex flex-row items-start justify-start min-w-[200] gap-2 hover:flex hover:flex-1 hover:h-[99px] hover:flex-row gap-2 hover:items-start hover:justify-start hover:min-w-[200]">
              <div className="h-[99px] flex-1 flex flex-col items-start justify-start gap-4 hover:flex hover:flex-1 hover:h-[99px] hover:flex-col gap-4 hover:items-start hover:justify-start h-[99px] flex-1 flex flex-col items-start justify-start gap-4 hover:flex hover:flex-1 hover:h-[99px] hover:flex-col gap-4 hover:items-start hover:justify-start">
                <div className="w-auto h-[43px] flex flex-col items-start justify-start gap-1 self-stretch hover:flex hover:self-stretch hover:w-auto hover:h-[43px] hover:flex-col gap-1 hover:items-start hover:justify-start w-auto h-[43px] flex flex-col items-start justify-start gap-1 self-stretch hover:flex hover:self-stretch hover:w-auto hover:h-[43px] hover:flex-col gap-1 hover:items-start hover:justify-start">
                  <div className="w-auto h-[22px] flex flex-row items-start justify-between self-stretch gap-0 hover:flex hover:self-stretch hover:w-auto hover:h-[22px] hover:flex-row gap-0 hover:items-start hover:justify-between w-auto h-[22px] flex flex-row items-start justify-between self-stretch gap-0 hover:flex hover:self-stretch hover:w-auto hover:h-[22px] hover:flex-row gap-0 hover:items-start hover:justify-between">
                    <div className="h-auto flex-1 relative leading-[21.6px] flex hover:font-nds-typography-library-body-text-small hover:text-lg hover:leading-[21.6px] hover:text-left hover:text-nds-refresh-neutrals-500 hover:flex hover:flex-1 hover:h-auto h-auto flex-1 relative leading-[21.6px] flex hover:font-nds-typography-library-body-text-small hover:text-lg hover:leading-[21.6px] hover:text-left hover:text-nds-refresh-neutrals-500 hover:flex hover:flex-1 hover:h-auto">
                      High Domestic Water Flow
                    </div>
                    <div className="h-auto w-32 relative text-sm tracking-[-0.5px] leading-[16.8px] text-gray-100 flex whitespace-nowrap hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.5px] hover:leading-[16.8px] hover:text-left hover:text-gray-100 hover:flex hover:w-32 hover:h-auto hover:whitespace-nowrap h-auto w-32 relative tracking-[-0.5px] leading-[16.8px] flex whitespace-nowrap hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.5px] hover:leading-[16.8px] hover:text-left hover:text-gray-100 hover:flex hover:w-32 hover:h-auto hover:whitespace-nowrap">
                      Yesterday, 08:00 AM
                    </div>
                  </div>
                  <div className="w-[828.5px] h-auto relative text-sm tracking-[-0.15px] leading-[17px] font-light text-nds-refresh-neutrals-400 flex hover:font-light hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.15px] hover:leading-[17px] hover:text-left hover:text-nds-refresh-neutrals-400 hover:flex hover:w-[828.5px] hover:h-auto w-[828.5px] h-auto relative tracking-[-0.15px] leading-[17px] font-light text-nds-refresh-neutrals-400 flex hover:font-light hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.15px] hover:leading-[17px] hover:text-left hover:text-nds-refresh-neutrals-400 hover:flex hover:w-[828.5px] hover:h-auto">
                    Increased water flow outside of normal range detected may
                    indicating potential water leak.
                  </div>
                </div>
                <div className="w-[138px] h-10 rounded-sm border-gray-200 border-[1px] border-solid box-border flex flex-row items-center justify-center py-2.5 px-[23px] gap-2.5 text-center text-base text-gray-200 hover:flex hover:w-[138px] hover:h-10 hover:flex-row gap-2.5 hover:items-center hover:justify-center hover:rounded-sm hover:py-2.5 hover:px-[23px] hover:box-border hover:border-gray-200 hover:border-[1px] hover:border-solid w-[138px] h-10 rounded-sm border-gray-200 border-[1px] border-solid box-border flex flex-row items-center justify-center py-2.5 px-[23px] gap-2.5 text-base text-gray-200 hover:flex hover:w-[138px] hover:h-10 hover:flex-row gap-2.5 hover:items-center hover:justify-center hover:rounded-sm hover:py-2.5 hover:px-[23px] hover:box-border hover:border-gray-200 hover:border-[1px] hover:border-solid">
                  <div className="h-auto w-[90px] relative tracking-[-0.2px] leading-[19.2px] font-light flex hover:font-light hover:font-nds-typography-library-body-text-small hover:text-base hover:tracking-[-0.2px] hover:leading-[19.2px] hover:text-center hover:text-gray-200 hover:flex hover:w-[90px] hover:h-auto h-auto w-[90px] relative tracking-[-0.2px] leading-[19.2px] font-light flex hover:font-light hover:font-nds-typography-library-body-text-small hover:text-base hover:tracking-[-0.2px] hover:leading-[19.2px] hover:text-center hover:text-gray-200 hover:flex hover:w-[90px] hover:h-auto">
                    View Details
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="self-stretch shadow-[0px_0px_0px_1px_#e7ecf0] bg-nds-refresh-neutrals-00white overflow-y-auto flex flex-col items-start justify-center p-4 box-border min-h-[48] w-auto h-auto gap-0 hover:bg-nds-refresh-neutrals-00white hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-col gap-0 hover:items-start hover:justify-center hover:p-4 hover:box-border hover:shadow-[0px_0px_0px_1px_#e7ecf0] hover:min-h-[48] self-stretch shadow-[0px_0px_0px_1px_#e7ecf0] bg-nds-refresh-neutrals-00white overflow-y-auto flex flex-col items-start justify-center p-4 box-border min-h-[48] w-auto h-auto gap-0 text-center text-sm text-gray-100 hover:bg-nds-refresh-neutrals-00white hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-col gap-0 hover:items-start hover:justify-center hover:p-4 hover:box-border hover:shadow-[0px_0px_0px_1px_#e7ecf0] hover:min-h-[48] self-stretch shadow-[0px_0px_0px_1px_#e7ecf0] bg-nds-refresh-neutrals-00white overflow-y-auto flex flex-col items-start justify-center p-4 box-border min-h-[48] w-auto h-auto gap-0 text-base text-nds-refresh-neutrals-400 hover:bg-nds-refresh-neutrals-00white hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-col gap-0 hover:items-start hover:justify-center hover:p-4 hover:box-border hover:shadow-[0px_0px_0px_1px_#e7ecf0] hover:min-h-[48]">
        <div className="self-stretch h-[99px] shrink-0 flex flex-row items-start justify-end gap-4 w-auto hover:flex hover:self-stretch hover:w-auto hover:h-[99px] hover:flex-row gap-4 hover:items-start hover:justify-end self-stretch h-[99px] shrink-0 flex flex-row items-start justify-end gap-4 w-auto hover:flex hover:self-stretch hover:w-auto hover:h-[99px] hover:flex-row gap-4 hover:items-start hover:justify-end self-stretch h-[99px] shrink-0 flex flex-row items-start justify-end gap-4 w-auto hover:flex hover:self-stretch hover:w-auto hover:h-[99px] hover:flex-row gap-4 hover:items-start hover:justify-end">
          <img
            className="h-[17.5px] w-[17.5px] relative bg-nds-colors-library-secondary-accent-blue600 flex hover:bg-nds-colors-library-secondary-accent-blue600 hover:flex hover:w-[17.5px] hover:h-[17.5px] h-[17.5px] w-[17.5px] relative bg-nds-colors-library-secondary-accent-blue600 flex hover:bg-nds-colors-library-secondary-accent-blue600 hover:flex hover:w-[17.5px] hover:h-[17.5px] h-[17.5px] w-[17.5px] relative bg-nds-colors-library-secondary-accent-blue600 flex hover:bg-nds-colors-library-secondary-accent-blue600 hover:flex hover:w-[17.5px] hover:h-[17.5px]"
            alt=""
            src="/vector-3.svg"
          />
          <div className="h-[99px] flex-1 flex flex-row flex-wrap items-center justify-end gap-4 hover:flex hover:flex-1 hover:h-[99px] hover:flex-row hover:flex-wrap gap-4 hover:items-center hover:justify-end h-[99px] flex-1 flex flex-row flex-wrap items-center justify-end gap-4 hover:flex hover:flex-1 hover:h-[99px] hover:flex-row hover:flex-wrap gap-4 hover:items-center hover:justify-end h-[99px] flex-1 flex flex-row flex-wrap items-center justify-end gap-4 hover:flex hover:flex-1 hover:h-[99px] hover:flex-row hover:flex-wrap gap-4 hover:items-center hover:justify-end">
            <div className="h-[99px] flex-1 flex flex-row items-start justify-start min-w-[200] gap-2 hover:flex hover:flex-1 hover:h-[99px] hover:flex-row gap-2 hover:items-start hover:justify-start hover:min-w-[200] h-[99px] flex-1 flex flex-row items-start justify-start min-w-[200] gap-2 hover:flex hover:flex-1 hover:h-[99px] hover:flex-row gap-2 hover:items-start hover:justify-start hover:min-w-[200] h-[99px] flex-1 flex flex-row items-start justify-start min-w-[200] gap-2 hover:flex hover:flex-1 hover:h-[99px] hover:flex-row gap-2 hover:items-start hover:justify-start hover:min-w-[200]">
              <div className="h-[99px] flex-1 flex flex-col items-start justify-start gap-4 hover:flex hover:flex-1 hover:h-[99px] hover:flex-col gap-4 hover:items-start hover:justify-start h-[99px] flex-1 flex flex-col items-start justify-start gap-4 hover:flex hover:flex-1 hover:h-[99px] hover:flex-col gap-4 hover:items-start hover:justify-start h-[99px] flex-1 flex flex-col items-start justify-start gap-4 hover:flex hover:flex-1 hover:h-[99px] hover:flex-col gap-4 hover:items-start hover:justify-start">
                <div className="w-auto h-[43px] flex flex-col items-start justify-start gap-1 self-stretch hover:flex hover:self-stretch hover:w-auto hover:h-[43px] hover:flex-col gap-1 hover:items-start hover:justify-start w-auto h-[43px] flex flex-col items-start justify-start gap-1 self-stretch hover:flex hover:self-stretch hover:w-auto hover:h-[43px] hover:flex-col gap-1 hover:items-start hover:justify-start w-auto h-[43px] flex flex-col items-start justify-start gap-1 self-stretch hover:flex hover:self-stretch hover:w-auto hover:h-[43px] hover:flex-col gap-1 hover:items-start hover:justify-start">
                  <div className="w-auto h-[22px] flex flex-row items-start justify-between self-stretch gap-0 hover:flex hover:self-stretch hover:w-auto hover:h-[22px] hover:flex-row gap-0 hover:items-start hover:justify-between w-auto h-[22px] flex flex-row items-start justify-between self-stretch gap-0 hover:flex hover:self-stretch hover:w-auto hover:h-[22px] hover:flex-row gap-0 hover:items-start hover:justify-between w-auto h-[22px] flex flex-row items-start justify-between self-stretch gap-0 hover:flex hover:self-stretch hover:w-auto hover:h-[22px] hover:flex-row gap-0 hover:items-start hover:justify-between">
                    <div className="h-auto flex-1 relative leading-[21.6px] flex hover:font-nds-typography-library-body-text-small hover:text-lg hover:leading-[21.6px] hover:text-left hover:text-nds-refresh-neutrals-500 hover:flex hover:flex-1 hover:h-auto h-auto flex-1 relative leading-[21.6px] flex hover:font-nds-typography-library-body-text-small hover:text-lg hover:leading-[21.6px] hover:text-left hover:text-nds-refresh-neutrals-500 hover:flex hover:flex-1 hover:h-auto h-auto flex-1 relative leading-[21.6px] flex hover:font-nds-typography-library-body-text-small hover:text-lg hover:leading-[21.6px] hover:text-left hover:text-nds-refresh-neutrals-500 hover:flex hover:flex-1 hover:h-auto">
                      Excessive Co2 Levels in Zone
                    </div>
                    <div className="h-auto w-32 relative text-sm tracking-[-0.5px] leading-[16.8px] text-gray-100 flex whitespace-nowrap hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.5px] hover:leading-[16.8px] hover:text-left hover:text-gray-100 hover:flex hover:w-32 hover:h-auto hover:whitespace-nowrap h-auto w-32 relative tracking-[-0.5px] leading-[16.8px] flex whitespace-nowrap hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.5px] hover:leading-[16.8px] hover:text-left hover:text-gray-100 hover:flex hover:w-32 hover:h-auto hover:whitespace-nowrap h-auto w-32 relative tracking-[-0.5px] leading-[16.8px] flex whitespace-nowrap hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.5px] hover:leading-[16.8px] hover:text-left hover:text-gray-100 hover:flex hover:w-32 hover:h-auto hover:whitespace-nowrap">
                      Yesterday, 08:00 AM
                    </div>
                  </div>
                  <div className="w-[828.5px] h-auto relative text-sm tracking-[-0.15px] leading-[17px] font-light text-nds-refresh-neutrals-400 flex hover:font-light hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.15px] hover:leading-[17px] hover:text-left hover:text-nds-refresh-neutrals-400 hover:flex hover:w-[828.5px] hover:h-auto w-[828.5px] h-auto relative tracking-[-0.15px] leading-[17px] font-light text-nds-refresh-neutrals-400 flex hover:font-light hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.15px] hover:leading-[17px] hover:text-left hover:text-nds-refresh-neutrals-400 hover:flex hover:w-[828.5px] hover:h-auto w-[828.5px] h-auto relative tracking-[-0.15px] leading-[17px] font-light flex hover:font-light hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.15px] hover:leading-[17px] hover:text-left hover:text-nds-refresh-neutrals-400 hover:flex hover:w-[828.5px] hover:h-auto">
                    This could indicate insufficient outside airflow into zones
                    impacted.
                  </div>
                </div>
                <div className="w-[138px] h-10 rounded-sm border-gray-200 border-[1px] border-solid box-border flex flex-row items-center justify-center py-2.5 px-[23px] gap-2.5 text-center text-base text-gray-200 hover:flex hover:w-[138px] hover:h-10 hover:flex-row gap-2.5 hover:items-center hover:justify-center hover:rounded-sm hover:py-2.5 hover:px-[23px] hover:box-border hover:border-gray-200 hover:border-[1px] hover:border-solid w-[138px] h-10 rounded-sm border-gray-200 border-[1px] border-solid box-border flex flex-row items-center justify-center py-2.5 px-[23px] gap-2.5 text-base text-gray-200 hover:flex hover:w-[138px] hover:h-10 hover:flex-row gap-2.5 hover:items-center hover:justify-center hover:rounded-sm hover:py-2.5 hover:px-[23px] hover:box-border hover:border-gray-200 hover:border-[1px] hover:border-solid w-[138px] h-10 rounded-sm border-gray-200 border-[1px] border-solid box-border flex flex-row items-center justify-center py-2.5 px-[23px] gap-2.5 text-gray-200 hover:flex hover:w-[138px] hover:h-10 hover:flex-row gap-2.5 hover:items-center hover:justify-center hover:rounded-sm hover:py-2.5 hover:px-[23px] hover:box-border hover:border-gray-200 hover:border-[1px] hover:border-solid">
                  <div className="h-auto w-[90px] relative tracking-[-0.2px] leading-[19.2px] font-light flex hover:font-light hover:font-nds-typography-library-body-text-small hover:text-base hover:tracking-[-0.2px] hover:leading-[19.2px] hover:text-center hover:text-gray-200 hover:flex hover:w-[90px] hover:h-auto h-auto w-[90px] relative tracking-[-0.2px] leading-[19.2px] font-light flex hover:font-light hover:font-nds-typography-library-body-text-small hover:text-base hover:tracking-[-0.2px] hover:leading-[19.2px] hover:text-center hover:text-gray-200 hover:flex hover:w-[90px] hover:h-auto h-auto w-[90px] relative tracking-[-0.2px] leading-[19.2px] font-light flex hover:font-light hover:font-nds-typography-library-body-text-small hover:text-base hover:tracking-[-0.2px] hover:leading-[19.2px] hover:text-center hover:text-gray-200 hover:flex hover:w-[90px] hover:h-auto">
                    View Details
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="self-stretch shadow-[0px_0px_0px_1px_#e7ecf0] bg-nds-refresh-neutrals-00white overflow-hidden flex flex-col items-start justify-center p-4 box-border min-h-[48] max-w-full w-auto h-auto gap-0 hover:bg-nds-refresh-neutrals-00white hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-col gap-0 hover:items-start hover:justify-center hover:p-4 hover:box-border hover:shadow-[0px_0px_0px_1px_#e7ecf0] hover:min-h-[48] hover:max-w-full self-stretch shadow-[0px_0px_0px_1px_#e7ecf0] bg-nds-refresh-neutrals-00white overflow-hidden flex flex-col items-start justify-center p-4 box-border min-h-[48] max-w-full w-auto h-auto gap-0 hover:bg-nds-refresh-neutrals-00white hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-col gap-0 hover:items-start hover:justify-center hover:p-4 hover:box-border hover:shadow-[0px_0px_0px_1px_#e7ecf0] hover:min-h-[48] hover:max-w-full">
        <div className="self-stretch flex flex-row flex-wrap items-start justify-end gap-4 max-w-full w-auto h-auto hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-row hover:flex-wrap gap-4 hover:items-start hover:justify-end hover:max-w-full self-stretch flex flex-row flex-wrap items-start justify-end gap-4 max-w-full w-auto h-auto hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-row hover:flex-wrap gap-4 hover:items-start hover:justify-end hover:max-w-full">
          <img
            className="h-[17.5px] w-[17.5px] relative bg-nds-colors-library-secondary-accent-blue600 flex hover:bg-nds-colors-library-secondary-accent-blue600 hover:flex hover:w-[17.5px] hover:h-[17.5px] h-[17.5px] w-[17.5px] relative bg-nds-colors-library-secondary-accent-blue600 flex hover:bg-nds-colors-library-secondary-accent-blue600 hover:flex hover:w-[17.5px] hover:h-[17.5px]"
            alt=""
            src="/vector-3.svg"
          />
          <div className="flex-1 flex flex-row flex-wrap items-center justify-end min-w-[538] max-w-full h-auto gap-4 hover:flex hover:flex-1 hover:h-auto hover:flex-row hover:flex-wrap gap-4 hover:items-center hover:justify-end hover:min-w-[538] hover:max-w-full mq975:min-w-full flex-1 flex flex-row flex-wrap items-center justify-end min-w-[538] max-w-full h-auto gap-4 hover:flex hover:flex-1 hover:h-auto hover:flex-row hover:flex-wrap gap-4 hover:items-center hover:justify-end hover:min-w-[538] hover:max-w-full mq975:min-w-full">
            <div className="flex-1 flex flex-row items-start justify-start min-w-[200] max-w-full h-auto gap-2 hover:flex hover:flex-1 hover:h-auto hover:flex-row gap-2 hover:items-start hover:justify-start hover:min-w-[200] hover:max-w-full flex-1 flex flex-row items-start justify-start min-w-[200] max-w-full h-auto gap-2 hover:flex hover:flex-1 hover:h-auto hover:flex-row gap-2 hover:items-start hover:justify-start hover:min-w-[200] hover:max-w-full">
              <div className="flex-1 flex flex-col items-start justify-start gap-4 max-w-full h-auto hover:flex hover:flex-1 hover:h-auto hover:flex-col gap-4 hover:items-start hover:justify-start hover:max-w-full flex-1 flex flex-col items-start justify-start gap-4 max-w-full h-auto hover:flex hover:flex-1 hover:h-auto hover:flex-col gap-4 hover:items-start hover:justify-start hover:max-w-full">
                <div className="self-stretch flex flex-col items-start justify-start gap-1 max-w-full w-auto h-auto hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-col gap-1 hover:items-start hover:justify-start hover:max-w-full self-stretch flex flex-col items-start justify-start gap-1 max-w-full w-auto h-auto hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-col gap-1 hover:items-start hover:justify-start hover:max-w-full">
                  <div className="self-stretch flex flex-row items-start justify-between [row-gap:20px] max-w-full gap-0 w-auto h-auto hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-row gap-0 hover:items-start hover:justify-between hover:[row-gap:20px] hover:max-w-full mq1000:flex-wrap self-stretch flex flex-row items-start justify-between [row-gap:20px] max-w-full gap-0 w-auto h-auto hover:flex hover:self-stretch hover:w-auto hover:h-auto hover:flex-row gap-0 hover:items-start hover:justify-between hover:[row-gap:20px] hover:max-w-full mq1000:flex-wrap">
                    <div className="w-[700.5px] relative leading-[22px] flex max-w-full h-auto hover:font-nds-typography-library-body-text-small hover:text-lg hover:leading-[22px] hover:text-left hover:text-nds-refresh-neutrals-500 hover:flex hover:w-[700.5px] hover:h-auto hover:max-w-full w-[700.5px] relative leading-[22px] flex max-w-full h-auto hover:font-nds-typography-library-body-text-small hover:text-lg hover:leading-[22px] hover:text-left hover:text-nds-refresh-neutrals-500 hover:flex hover:w-[700.5px] hover:h-auto hover:max-w-full">
                      High Humidity Condition
                    </div>
                    <div className="w-32 relative text-sm tracking-[-0.5px] leading-[17px] text-gray-100 flex whitespace-nowrap h-auto hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.5px] hover:leading-[17px] hover:text-left hover:text-gray-100 hover:flex hover:w-32 hover:h-auto hover:whitespace-nowrap w-32 relative tracking-[-0.5px] leading-[17px] flex whitespace-nowrap h-auto hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.5px] hover:leading-[17px] hover:text-left hover:text-gray-100 hover:flex hover:w-32 hover:h-auto hover:whitespace-nowrap">
                      Yesterday, 08:00 AM
                    </div>
                  </div>
                  <div className="self-stretch relative text-sm tracking-[-0.15px] leading-[17px] font-light text-nds-refresh-neutrals-400 flex w-auto h-auto hover:font-light hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.15px] hover:leading-[17px] hover:text-left hover:text-nds-refresh-neutrals-400 hover:flex hover:self-stretch hover:w-auto hover:h-auto self-stretch relative tracking-[-0.15px] leading-[17px] font-light text-nds-refresh-neutrals-400 flex w-auto h-auto hover:font-light hover:font-nds-typography-library-body-text-small hover:text-sm hover:tracking-[-0.15px] hover:leading-[17px] hover:text-left hover:text-nds-refresh-neutrals-400 hover:flex hover:self-stretch hover:w-auto hover:h-auto">{`Excessive humidity sensed across 2 zones resulting in 240 indicating potential mechanical failure. `}</div>
                </div>
                <div className="w-[138px] rounded-sm border-gray-200 border-[1px] border-solid box-border flex flex-row items-center justify-center py-2 px-[23px] h-auto gap-2.5 text-center text-base text-gray-200 hover:flex hover:w-[138px] hover:h-auto hover:flex-row gap-2.5 hover:items-center hover:justify-center hover:rounded-sm hover:py-2 hover:px-[23px] hover:box-border hover:border-gray-200 hover:border-[1px] hover:border-solid w-[138px] rounded-sm border-gray-200 border-[1px] border-solid box-border flex flex-row items-center justify-center py-2 px-[23px] h-auto gap-2.5 text-base text-gray-200 hover:flex hover:w-[138px] hover:h-auto hover:flex-row gap-2.5 hover:items-center hover:justify-center hover:rounded-sm hover:py-2 hover:px-[23px] hover:box-border hover:border-gray-200 hover:border-[1px] hover:border-solid">
                  <div className="flex-1 relative tracking-[-0.2px] leading-[20px] font-light flex h-auto hover:font-light hover:font-nds-typography-library-body-text-small hover:text-base hover:tracking-[-0.2px] hover:leading-[20px] hover:text-center hover:text-gray-200 hover:flex hover:flex-1 hover:h-auto flex-1 relative tracking-[-0.2px] leading-[20px] font-light flex h-auto hover:font-light hover:font-nds-typography-library-body-text-small hover:text-base hover:tracking-[-0.2px] hover:leading-[20px] hover:text-center hover:text-gray-200 hover:flex hover:flex-1 hover:h-auto">
                    View Details
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
};

NotificationPanel.propTypes = {
  className: PropTypes.string,
};

export default NotificationPanel;
